# Stage 1: Build
FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /build

COPY src/Main.java .

RUN javac Main.java


# Stage 2: Runtime 
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /build/Main.class .


CMD ["java", "Main"]